# Currently this workflow does not automatically pull in changes from internal or create a git tag or Github "Release". First 
# make sure to manually create a release commit in internal/master updating the version number in the `Library/mparticle.nuspec`
# file. Then push internal/master to public/master and run this workflow from public/master to build and release to nuget. 
# After it's released to nuget, manually create a tag and "Release" in the public repo pointing to the release commit.

name: Release SDK

on:
    workflow_dispatch:

jobs:
    # SDK release is done from public/master branch.
    confirm-master-branch:
        name: Confirm release is run on public/master branch
        runs-on: ubuntu-latest
        steps:
            - name: Git checkout
              uses: actions/checkout@v2
            - name: Branch name
              run: |
                  BRANCHNAME=${GITHUB_REF##*/}
                  echo "pulling branch name, branch name is:"
                  echo $BRANCHNAME
                  if [ $BRANCHNAME != "master" ]
                  then
                    echo "You can only run a release from the master branch, you are trying to run it from ${BRANCHNAME}"
                    exit 1
                  fi

    release-to-nuget:
        name: Release and Sync Repos
        runs-on: macos-latest
        needs: ['confirm-master-branch']
        steps:
            - name: Git checkout
              uses: actions/checkout@v2
            - name: Build artifacts
              run: ./build.sh
            - name: Release to Nuget
              run: nuget push *.nupkg ${{ secrets.NUGET_API_KEY }} -Source https://api.nuget.org/v3/index.json
